# Generated by Django 5.1.15 on 2026-02-09 08:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('siren', models.CharField(blank=True, max_length=9)),
                ('siret', models.CharField(blank=True, max_length=14)),
                ('vat_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('electronic_address', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('response_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('invoice_type_code', models.CharField(default='380', max_length=10)),
                ('currency_code', models.CharField(default='EUR', max_length=3)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('processing', 'En cours de génération'), ('validated', 'Validée'), ('transmitted', 'Transmise'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('total_excl_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_incl_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('en16931_data', models.JSONField(default=dict)),
                ('facturx_status', models.CharField(blank=True, max_length=20)),
                ('pdp_transmission_id', models.CharField(blank=True, max_length=100)),
                ('pdp_status', models.CharField(blank=True, max_length=50)),
                ('factpulse_error', models.JSONField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('pdf_file', models.FileField(blank=True, upload_to='invoices/pdf/')),
                ('is_internal', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NumberingCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_prefix', models.CharField(db_index=True, max_length=100)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NumberingSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_template', models.CharField(default="FACT-{{ issue_date|date:'Y' }}-", max_length=100)),
                ('padding', models.PositiveIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('default_unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('default_vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('default_vat_category', models.CharField(default='S', max_length=5)),
                ('default_unit', models.CharField(default='C62', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('siren', models.CharField(blank=True, max_length=9)),
                ('siret', models.CharField(blank=True, max_length=14)),
                ('vat_number', models.CharField(blank=True, max_length=20)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('bic', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('electronic_address', models.JSONField(blank=True, default=dict)),
                ('legal_description', models.CharField(blank=True, max_length=500)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, upload_to='suppliers/logos/')),
                ('primary_color', models.CharField(blank=True, max_length=7)),
                ('pdf_legal_mentions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
