# Generated by Django 5.1.15 on 2026-02-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='note_aab',
            field=models.TextField(blank=True, default="Pas d'escompte"),
        ),
        migrations.AddField(
            model_name='supplier',
            name='note_pmd',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='note_pmt',
            field=models.TextField(blank=True, default='Indemnité forfaitaire pour frais de recouvrement : 40 €'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms_end_of_month',
            field=models.BooleanField(default=False),
        ),
    ]
