# Generated by Django 5.1.15 on 2026-02-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_supplier_notes_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
