# Generated by Django 5.1.15 on 2026-02-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_archived_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='note_pmd',
            field=models.TextField(blank=True, default="Pénalités de retard : 3 fois le taux d'intérêt légal"),
        ),
    ]
