# Generated by Django 5.1.15 on 2026-02-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_supplier_note_pmd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('processing', 'En cours de génération'), ('validated', 'Validée'), ('transmitting', 'Transmission en cours'), ('transmitted', 'Transmise'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='draft', max_length=20),
        ),
    ]
