# Generated by Django 5.1.15 on 2026-02-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_add_transmitting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cdar_flow_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
