# Generated by Django 5.1.15 on 2026-02-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_add_cdar_flow_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('processing', 'En cours de génération'), ('validated', 'Validée'), ('transmitting', 'Transmission en cours'), ('transmitted', 'Transmise'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('refused', 'Refusée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='draft', max_length=20),
        ),
    ]
