# Generated by Django 5.1.15 on 2026-02-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_add_refused_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='cdar_flow_id',
        ),
    ]
