# Generated by Django 5.1.15 on 2026-02-23 07:00

import apps.billing.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_add_org_number_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='invoices/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), apps.billing.validators.validate_pdf_size]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(blank=True, upload_to='suppliers/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg']), apps.billing.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Invalid hex color.')]),
        ),
    ]
