# Generated by Django 5.1.15 on 2026-03-05 08:37

import apps.billing.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_invoice_pdf_file_alter_supplier_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(blank=True, upload_to='suppliers/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.billing.validators.validate_image_size]),
        ),
    ]
