# Generated by Django 5.1.15 on 2026-03-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_supplier_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('assujetti_fr', 'Assujetti TVA France'), ('intra_ue', 'Intra-communautaire UE'), ('extra_ue', 'Extra-UE'), ('particulier', 'Particulier (B2C)'), ('public', 'Secteur public (B2G)')], default='assujetti_fr', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='detected_flow',
            field=models.CharField(blank=True, choices=[('b2b_domestic', 'B2B domestique (e-facturation)'), ('b2c', 'B2C (e-reporting)'), ('b2b_intra_eu', 'B2B intra-UE (e-reporting)'), ('b2b_extra_eu', 'B2B extra-UE (e-reporting)'), ('b2g', 'B2G (Chorus Pro)')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='operation_category',
            field=models.CharField(choices=[('TPS1', 'Prestation de services'), ('TLB1', 'Livraison de biens'), ('TNT1', 'Opérations non taxées'), ('TMA1', 'Mixte')], default='TPS1', max_length=4),
        ),
    ]
