# Generated by Django 5.1.15 on 2026-03-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_flow_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ereporting_error',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ereporting_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('pending', 'En attente'), ('submitted', 'Soumis'), ('accepted', 'Accepté'), ('error', 'Erreur')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='vat_regime',
            field=models.CharField(choices=[('reel_normal_mensuel', 'Réel normal mensuel'), ('reel_normal_trimestriel', 'Réel normal trimestriel'), ('simplifie', 'Simplifié'), ('franchise', 'Franchise en base')], default='reel_normal_mensuel', max_length=30),
        ),
    ]
