# Generated by Django 5.1.15 on 2026-03-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_ereporting_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Créé'), ('status_change', 'Changement de statut'), ('delete', 'Suppression'), ('flow_submitted', 'Flux soumis'), ('cdar_event', 'Événement CDAR'), ('cdar_paid_submitted', 'CDAR payé soumis'), ('cdar_paid_skipped', 'CDAR payé ignoré'), ('cdar_paid_error', 'CDAR payé erreur'), ('data_update', 'Mise à jour des données'), ('ereporting_submitted', 'E-reporting soumis'), ('ereporting_error', 'E-reporting erreur')], max_length=50),
        ),
    ]
