# Generated by Django 5.1.15 on 2026-02-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='factpulse_client_uid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
