# Generated by Django 5.1.15 on 2026-03-04 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_profiles_for_existing_users(apps, schema_editor):
    """Mark all pre-existing users as email-verified."""
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("core", "UserProfile")
    profiles = [
        UserProfile(user=user, email_verified=True)
        for user in User.objects.filter(profile__isnull=True)
    ]
    UserProfile.objects.bulk_create(profiles)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_factpulse_client_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            create_profiles_for_existing_users,
            migrations.RunPython.noop,
        ),
    ]
